### ISSUE TITLE
Compile fails on current master

### ISSUE THREAD

**Issue by trondhindenes** [Netflix/vizceral-example#19] opened 2016-11-15 16:28 UTC
After pulling in the latest changes, I'm getting this compiler error when trying to run `npm run dev`:

```
ERROR in ./src/app.jsx
Module build failed: Error: Cannot find module './_an-object' (While processing preset: "c:\\Users\\trond\\Documents\\projects\\vizceral-example\\node_modules\\babel-preset-es2015\\lib\\index.js")
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:\Users\trond\Documents\projects\vizceral-example\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-regenerator\node_modules\babel-runtime\node_modules\core-js\library\modules\_object-dp.js:1:84)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:\Users\trond\Documents\projects\vizceral-example\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-regenerator\node_modules\babel-runtime\node_modules\core-js\library\modules\_hide.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by jrsquared** [comment] 2016-11-15 17:59
In a clean clone on my Mac, I do not see this error.  Did you make sure you have all the latest dependencies? I do not have a Windows machine handy to test on to see if it's platform specific.

**Comment by jrsquared** [comment] 2016-11-23 18:31
Closing since I am unable to reproduce and no more active discussion. Please re-open if you continue to have problems and have some more information.

**Closed by jrsquared** 2016-11-23 18:31 UTC

**Comment by trondhindenes** [comment] 2016-11-23 20:17
Sorry I didn't provide any follow-up feedback. Was unable to repro myself, after I re-cloned the repo.
